### ISSUE TITLE
Adicionar ao F-Droid

### ISSUE THREAD

**Issue by pizzamaker** [pedrofsn/android-CorHexadecimalSimples#2]
Seria muito bacana ter esse app no F-Droid, que é uma espécie de Google Play mas com apenas software livre: https://f-droid.org/

Aqui tem instruções de como adicioná-lo à fila de inclusão: https://f-droid.org/contribute/

**Comment by pedrofsn** [comment]
@pizzamaker, interessante, mas o manual não está claro o suficiente.

**Comment by pedrofsn** [comment]
Este link continha instruções mais detalhadas, https://f-droid.org/wiki/page/Inclusion_How-To.
Postei o app na fila de submissão, https://f-droid.org/forums/forum/submission-queue/.
